import { gql } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { apollo } from "../services/apollo";
import styles from "../styles/Home.module.css";
import { LinkProps } from "../types/link";

type TypeProps = {
  links: LinkProps[];
};

const Home: NextPage = ({ links }: TypeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>GraphQL and Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Lista de links</h1>

        <p className={styles.description}>Total de links: {links.length}</p>

        <div className={styles.grid}>
          {links.map((link) => (
            <a
              key={link.id}
              href={`https://${link.url}`}
              className={styles.card}
              rel="noreferrer"
              target="_blank"
            >
              <h2>{link.title}</h2>
              <p>{link.url}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const { data } = await apollo.query({
    query: gql`
      query {
        links {
          id
          title
          url
        }
      }
    `,
  });

  return {
    props: {
      links: data.links,
    },
  };
};
